### ISSUE TITLE
Single quote in the name and path is a bad idea

### ISSUE THREAD

**Issue by SoftExpert** [simtrami/posy-improved-cursor-linux#1]
Hello,

First of all, great work ! It's a pleasant cursor theme to use.
One small complaint, though - the single quote in the name and path is a bad idea, since QML parsing in KDE will complain about the non closed quote, and might even stop parsing usefull stuff afterwards.

I would be good to get rid of the quote, I think - it invites unnecessary and unforeseen issues.

Cheers !

**Comment by aironsouza** [comment]
I agree. Cinnamon in particular seems to have problems with this ' in the name too.

**Comment by simtrami** [comment]
Hello,
I also agree, I should have anticipated this would be an issue. **Thank you for telling me!**
I will push the fix when I'm home after my holidays in the beginning of next week.

I hope you enjoy these cursors as much as I enjoy them 😊

**Comment by simtrami** [comment]
Hello,

I pushed the fix in the [1.5 update](https://github.com/simtrami/posy-improved-cursor-linux/tree/1.5) and uploaded the files to [pling.com](https://www.pling.com/p/1795042/). It should be available to your GUIs' stores in a few moments.

I wanted to rename the set from "Posy's improved cursor" to "Posy’s improved cursor" (with an apostrophe) but the form on the website wouldn't let me. **Let me know if you think the single quote in the set's name will be a curse if I leave it.**
