### ISSUE TITLE
Request for the left handed variant

### ISSUE THREAD

**Issue by SammyForReal** [simtrami/posy-improved-cursor-linux#11]
Hello.

First of: I appreciate this project and would like to thank you for this!

Since I am a left handed person, I actually always preferred the left handed variant by Posy. Now, I noticed that this project does not cover that variant however…

I tried doing this by myself using win2xcur, like mentioned in the README, but I just cannot get python to get running ^^'

**Comment by simtrami** [comment]
Closed by PR #14 (ee41173) and 76b6e31
Thank you @SammyForReal !
