### ISSUE TITLE
Add the 125% and 175% Scaled Cursors

### ISSUE THREAD

**Issue by Leonerd-04** [simtrami/posy-improved-cursor-linux#3]
The 125%/175% scaled set found on de Boer's website is notably missing. I think it might be worth adding, as for certain high dpi users, 100% can be too small while 150% is too large.

If I have some time I may be able to figure out how to contribute these myself.

**Comment by simtrami** [comment]
Hi! Thank you @Leonerd-04 for your suggestion :slightly_smiling_face: 
You are not the only one to request this, I will try to port them also when I have time.
I'll keep you up to date on this issue.

**Comment by simtrami** [comment]
Resolved by #5, thank you very much again !
