### ISSUE TITLE
KDE Cursors broken in store

### ISSUE THREAD

**Issue by Leonerd-04** [simtrami/posy-improved-cursor-linux#4]
Some of the cursors don't display properly when downloaded from the store. This can be shown simply with a screenshot from the UI in KDE Neon's Settings. On the left is the set installed from KDE Neon through the UI. On the right is the same set, manually cloned from GitHub. 
![image](https://user-images.githubusercontent.com/87563929/190007421-952fd74b-ed56-485f-93cc-d5027ea3e906.png)

**Comment by simtrami** [comment]
Yep, most of the other issues come to this : KDE store breaks the cursors when installing them. My only option is to publish new files and hope they magically work.

**Comment by simtrami** [comment]
Hi @Leonerd-04!

Do you have any update on this? Is it fixed or have you move on? I'd be interested in having your feedback on the new `.tar.xz` cursor packages.

**Comment by Leonerd-04** [comment]
Hello @simtrami, I just checked by redownloading from the KDE store and it appears the issue has been fixed; cursors display as they should. Thanks for your work.

**Comment by simtrami** [comment]
Fantastic, thank you!
