### ISSUE TITLE
Cursors not working

### ISSUE THREAD

**Issue by Lars-** [simtrami/posy-improved-cursor-linux#6]
![image](https://user-images.githubusercontent.com/5690934/202634627-c8ed6307-6c97-4470-9667-2c90fabf0974.png)

Hi,

First of all, thank you for making it possible at all, this is by far the best cursor set I've used (on Windows). I unfortunately can't get it to work on KDE... A lot of the icons seem unavailable. I tried using the store version (two days ago) and today the manual installation, but both don't work. My display scaling is 150% (maybe that has something to do with it).

Do you have any idea on how to fix this?

Thanks in advance,
Lars Jansen

**Comment by simtrami** [comment]
Hello Lars :wave: Thanks for the feedback!

You seem to be experiencing what I call (in my head) _the ghost install_ :ghost: 
I am using KDE too on multiple PCs (and multiple distros : Ubuntu, Fedora and Manjaro, please don't ask why), but I managed to have them all running my port of Posy's cursors. Though, never the first time.

My most recent installation, two weeks ago, added the Strokeless set on Ubuntu KDE via the KDE store. I installed the specific package (not the all-in-one) called `posy-s-cursor-strokeless.tar.xz` : previously, I had issues with the KDE cursor store corrupting installations via the `.tar.gz` packages, so maybe this tip that'll help.
The first time I install, there's always an already opened app (including KDE desktop) which, when hovered, changes my cursor to a previous or default one. To fix this, I can logout and log back, or live with it until it fixes itself after rebooting the PC the next day.

If you have installed the cursor set, from the store or manually, via a `.tar.xz` package, already rebooted and still experience the same or similar issues, I would be interested in having a screenshot of the content of the `~/.icons/<cursor package>/cursors` folder, similar to the one in this message : https://github.com/simtrami/posy-improved-cursor-linux/issues/2#issuecomment-1230923198

I look forward to your response and hope we'll fix this quickly so you can **finally** enjoy using your KDE desktop :wink: 

NB: If everything fixed itself magically, without doing anything or in a way you can't explain, please tell me anyway :pray:

**Comment by Lars-** [comment]
Hi @simtrami, 

Thank you for the response! 

> Ubuntu, Fedora and Manjaro, please don't ask why

Haha, okay, I won't 😬

Your solution fixed it, I removed the cursors from the .icons folder and then, like you said, installed it via de KDE store. For some reason it worked this time, so thank you! 

![image](https://user-images.githubusercontent.com/5690934/202988763-85286347-d83e-48c6-89c8-7b2164250e30.png)

**Comment by simtrami** [comment]
Hi Lars!

This is very good news, thank you for telling me!
In order to demystify a bit why it's working now and not then: yesterday, I removed the `tar.gz` packages from the store, thus only leaving the `tar.xz`. You must have had issues because you installed from a `.gz`initially.
I'm glad it works properly now!

Have a nice day!
